version: "3.9"
services:
  db:
    image: postgres
    ports:
      - "5438:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=deposir_bot
    volumes:
      - ./deposir_bot_data:/var/lib/postgresql/data